<?php

/**
 * Implementation of hook_form_alter().
 */
function grinnell_tweaks_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'islandora_extended_search_form':
      // Form modification code goes here.
      $keys = array_keys($form['terms']);
      $numeric_keys = array_filter($keys,'is_numeric');
      foreach ($numeric_keys as $key) {
        $form['terms'][$key]['field']['#value'] = 'text';
      }
      break;
  }
}

function grinnell_tweaks_islandora_solr_search_query_processor() {
  if (isset($_SESSION['scholar']['search']['sort'])) {
    return array('sort' => $_SESSION['scholar']['search']['sort']);
  }
}